### ISSUE TITLE
Allow specifying (more) arbitrary termination conditions

### ISSUE THREAD

**Issue by ISSOtm** [eievui5/evunit#10]
Currently, the test requires PC = 0xFFFF to return (and this is enforced on `ret` by pushing that to the stack just prior). It would be useful to specify other stop location(s), to unit test inlined code as well.

**Comment by DaKnig** [comment]
what types of termination conditions do you want? a different stop location? would love to hear input.
consider the fact that adding more complex stopping mechanisms adds more overhead *per instruction we run* as it is implemented currently.

**Comment by ISSOtm** [comment]
Stopping at a certain PC location seems to be the highest-value low-hanging fruit for now.

**Comment by DaKnig** [comment]
I think the best approach to this is to still set the PC location via the current approach of pushing that value to the stack. this means less checks per cycle emulated.
