### ISSUE TITLE
Explain how tests know when to end

### ISSUE THREAD

**Issue by Rangi42** [eievui5/evunit#19]
If I initialize a test with `pc = SomeRoutine`, I would expect it to end when the routine `ret`urns. But there are more complex cases. What about testing a routine that calls other routines, where they may `ret`urn? What about if `SomeRoutine` pops its return address off the stack and messes with it? Or if you start with `call SomeRoutine / dw SomeData`, and `SomeRoutine` pops its "return address" to use `SomeData` as an argument? Or if you're testing a whole ROM (so `pc` isn't initialized) and there may be interrupts?

**Comment by evie-calico** [comment]
At the moment, evunit pushes $FFFF to the stack before running your code, and when pc == $FFFF, the test is considered over. There’s an issue open to allow for more arbitrary end conditions.

**Comment by Rangi42** [comment]
Got it. I think it would be nice to explain that in the README even if it'll be improved eventually.
