### ISSUE TITLE
Missing HRAM emulation

### ISSUE THREAD

**Issue by elialm** [eievui5/evunit#30]
I've noticed that there's no emulation of memory transactions to HRAM looking at `memory.rs`, if I'm not mistaken. Is this a planned feature? I don't mind putting it in myself. I need it for a project I'm working on.

**Comment by evie-calico** [comment]
I'll try to get to this soon. Feel free to open a PR if you don't feel like waiting; it should be a very small change.

**Comment by elialm** [comment]
I've started a PR, see #31. It was indeed a small change.

**Comment by evie-calico** [comment]
Closed by #31!
