### ISSUE TITLE
Share ROM between tests

### ISSUE THREAD

**Issue by ISSOtm** [eievui5/evunit#4]
Currently, every test uses its own copy of the ROM (`Vec<u8>` in the `AddressSpace`); since ROM is immutable, it should be possible to instead take a `&[u8]` instead; this might conflict with #3, though, unless using something like `scoped_thread`.

**Comment by evie-calico** [comment]
These tests have been moved to https://github.com/eievui5/gb-cpu-sim

**Comment by ISSOtm** [comment]
I was saying that you should be able to create a new `AddressSpace` that only takes a reference to the ROM, instead of cloning an existing on with the embedded ROM:

https://github.com/eievui5/evunit/blob/498996527445449440f6f4f338faaf6966c0ecfa/src/main.rs#L396

**Comment by evie-calico** [comment]
Ah, I’m sorry! It gets kinda ambiguous when your unit testing program has its own unit tests.

**Comment by DaKnig** [comment]
I think adding an `Arc` around a reference to the ROM would do the job. but then, every time you start a test you have to make an atomic write to synchronize to the reference count. I wonder if it makes a difference on expected load.

**Comment by ISSOtm** [comment]
Evunit only really needs to be single-threaded, so a `Rc` is sufficient.

**Comment by evie-calico** [comment]
Actually I just took a reference to a Vec…
